In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('../datasets/ressource.csv', index_col=0)
df

SEQNUMC  SEQNUMHH  PDAT    PROVWT_D     RDDWT_D  STRATUM  YEAR  \
1       128521     12852     2         NaN  235.916956     1031  2017   
2        10741      1074     2         NaN  957.353840     1068  2017   
3       220011     22001     2         NaN  189.611299     1050  2017   
4        86131      8613     1  675.430817  333.447418     1040  2017   
5       227141     22714     1  482.617748  278.768063     1008  2017   
...        ...       ...   ...         ...         ...      ...   ...   
28461    19141      1914     2         NaN   21.188088     2062  2017   
28462   121401     12140     2         NaN   26.503010     2004  2017   
28463   128831     12883     2         NaN   27.520652     2004  2017   
28464    82921      8292     2         NaN   22.390587     2062  2017   
28465   244621     24462     2         NaN   27.520652     2004  2017   

       AGECPOXR  HAD_CPOX  AGEGRP  ...  XVRCTY2  XVRCTY3  XVRCTY4  XVRCTY5  \
1           NaN         2       1  ...                        NaN      NaN   
2           NaN         2       1  ...                        NaN      NaN   
3           NaN         2       3  ...                        NaN      NaN   
4           NaN         2       1  ...                        NaN      NaN   
5           NaN         2       1  ...                        NaN      NaN   
...         ...       ...     ...  ...      ...      ...      ...      ...   
28461       NaN         2       3  ...                        NaN      NaN   
28462       NaN         2       3  ...                        NaN      NaN   
28463       NaN         2       3  ...                        NaN      NaN   
28464       NaN         2       3  ...                        NaN      NaN   
28465       NaN         2       3  ...                        NaN      NaN   

       XVRCTY6  XVRCTY7  XVRCTY8  XVRCTY9  INS_STAT2_I  INS_BREAK_I  
1          NaN      NaN      NaN      NaN          NaN          NaN  
2          NaN      NaN      NaN      NaN          NaN          NaN  
3          NaN      NaN      NaN      NaN          NaN          NaN  
4          NaN      NaN      NaN      NaN          1.0          2.0  
5          NaN      NaN      NaN      NaN          2.0          1.0  
...        ...      ...      ...      ...          ...          ...  
28461      NaN      NaN      NaN      NaN          NaN          NaN  
28462      NaN      NaN      NaN      NaN          NaN          NaN  
28463      NaN      NaN      NaN      NaN          NaN          NaN  
28464      NaN      NaN      NaN      NaN          NaN          NaN  
28465      NaN      NaN      NaN      NaN          NaN          NaN  

[28465 rows x 453 columns]

In [6]:
df['EDUC1'] #see page 55 in "NIS-Child: A User's Guide for the 2017 PUF"

1        4
2        3
3        3
4        4
5        1
        ..
28461    3
28462    2
28463    3
28464    2
28465    4
Name: EDUC1, Length: 28465, dtype: int64

Q1: Write a function called proportion_of_education which returns the proportion of children in the dataset who had a mother with the education levels equal to less than high school (<12), high school (12), more than high school but not a college graduate (>12) and college degree.

This function should return a dictionary in the form of (use the correct numbers, do not round numbers):

    {"less than high school":0.2,
    "high school":0.4,
    "more than high school but not college":0.2,
    "college":0.2}

In [7]:
def proportion_of_education():
    
    education_levels = df['EDUC1']
    education_ranking = np.sort(education_levels.values)
    
    poe = {"less than high school": 0,
        "high school": 0,
        "more than high school but not college": 0,
        "college": 0}
    n = len(education_ranking)
    
    poe["less than high school"] = np.sum(education_ranking == 1)/n
    poe["high school"] = np.sum(education_ranking == 2)/n
    poe["more than high school but not college"] = np.sum(education_ranking == 3)/n
    poe["college"] = np.sum(education_ranking == 4)/n
    
    return poe

In [8]:
assert type(proportion_of_education())==type({}), "You must return a dictionary."
assert len(proportion_of_education()) == 4, "You have not returned a dictionary with four items in it."
assert "less than high school" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "high school" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "more than high school but not college" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "college" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."


all tests passed

Q2: Let's explore the relationship between being fed breastmilk as a child and getting a seasonal influenza vaccine from a healthcare provider. Return a tuple of the average number of influenza vaccines for those children we know received breastmilk as a child and those who know did not.

This function should return a tuple in the form (use the correct numbers:

(2.5, 0.1)

In [9]:
# Breastfeeding Variables
# CBF_01 – child ever fed breast milk (see page 52 "NIS-Child: A User's Guide for the 2017 PUF")

# Number of Provider-Reported Doses of Vaccine Variables
# P_NUMFLU – total number of seasonal influenza doses (see page 43 "NIS-Child: A User's Guide for the 2017 PUF")


In [10]:
relational_df = df[['CBF_01','P_NUMFLU']]
relational_df.head()

CBF_01  P_NUMFLU
1       1       NaN
2       2       NaN
3       2       NaN
4       2       3.0
5       1       0.0

In [11]:
relational_df.isna().sum()

CBF_01          0
P_NUMFLU    13132
dtype: int64

In [12]:
relational_df["CBF_01"].unique()

array([ 1,  2, 99, 77], dtype=int64)

In [13]:
relational_df["P_NUMFLU"].unique()

array([nan,  3.,  0.,  2.,  1.,  4.,  5.,  6.])

In [14]:
relational_df["CBF_01"] = relational_df["CBF_01"].replace(dict.fromkeys([99,77], 2))

C:\Users\hkhalifa\AppData\Local\Temp\ipykernel_16640\1743315041.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  relational_df["CBF_01"] = relational_df["CBF_01"].replace(dict.fromkeys([99,77], 2))


In [15]:
relational_df["CBF_01"].unique()

array([1, 2], dtype=int64)

In [16]:
relational_df.dropna(axis="rows", inplace=True)

C:\Users\hkhalifa\AppData\Local\Temp\ipykernel_16640\1198610770.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  relational_df.dropna(axis="rows", inplace=True)


In [17]:
relational_df

CBF_01  P_NUMFLU
4           2       3.0
5           1       0.0
7           1       0.0
8           1       0.0
9           1       0.0
...       ...       ...
28447       1       2.0
28448       2       1.0
28450       1       4.0
28453       2       2.0
28455       1       0.0

[15333 rows x 2 columns]

Write everything into a function


In [18]:
def average_influenza_doses():
    relational_df = df[['CBF_01','P_NUMFLU']]
    relational_df["CBF_01"] = relational_df["CBF_01"].replace(dict.fromkeys([99,77], 2))
    relational_df.dropna(axis="rows", inplace=True)

    cbf_1 = relational_df[relational_df['CBF_01'] == 1] #not breastfed
    cbf_2 = relational_df[relational_df['CBF_01'] == 2] #breastfed

    flu1 = cbf_1['P_NUMFLU']
    f1 = flu1.sum() / flu1.size

    flu2 = cbf_2['P_NUMFLU']
    f2 = flu2.sum() / flu2.size

    return (f1,f2)

In [19]:
assert len(average_influenza_doses())==2, "Return two values in a tuple, the first for yes and the second for no."

C:\Users\hkhalifa\AppData\Local\Temp\ipykernel_16640\3365313861.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  relational_df["CBF_01"] = relational_df["CBF_01"].replace(dict.fromkeys([99,77], 2))
C:\Users\hkhalifa\AppData\Local\Temp\ipykernel_16640\3365313861.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  relational_df.dropna(axis="rows", inplace=True)


# Question 3
It would be interesting to see if there is any evidence of a link between vaccine effectiveness and sex of the child. Calculate the ratio of the number of children who contracted chickenpox but were vaccinated against it (at least one varicella dose) versus those who were vaccinated but did not contract chicken pox. Return results by sex.

This function should return a dictionary in the form of (use the correct numbers):

    {"male":0.2,
    "female":0.4}
Note: To aid in verification, the chickenpox_by_sex()['female'] value the autograder is looking for starts with the digits 0.0077.

In [31]:
df.HAD_CPOX.unique()

array([ 2,  1, 77, 99], dtype=int64)

In [32]:
df = df.drop(df[df.HAD_CPOX == 77].index)
df = df.drop(df[df.HAD_CPOX == 99].index)

In [33]:
def chickenpox_by_sex():
    maleDf = df[df["SEX"] ==1]
    m_vaccinated = maleDf[maleDf["P_NUMVRC"] >= 1]
    m_no_cpox = m_vaccinated[m_vaccinated["HAD_CPOX"] == 2]
    m_no_cp_count = m_no_cpox["SEX"].count()
    m_cpox = m_vaccinated[m_vaccinated["HAD_CPOX"] == 1]
    m_cp_count = m_cpox["SEX"].count()
    resultMale = m_cp_count/m_no_cp_count

    femaleDf = df[df["SEX"] == 2]
    f_vaccinated = femaleDf[femaleDf["P_NUMVRC"] >= 1]
    f_cpox = f_vaccinated[f_vaccinated["HAD_CPOX"] == 1]
    count_f_cpox = f_cpox["SEX"].count()
    f_no_cpox = f_vaccinated[f_vaccinated["HAD_CPOX"] == 2]
    count_f_no_cpox = f_no_cpox["SEX"].count()
    resultFemale = count_f_cpox/count_f_no_cpox

    ratio_dict = {"male":resultMale,
            "female":resultFemale
        }   

    return ratio_dict

In [36]:
assert len(chickenpox_by_sex())==2, "Return a dictionary with two items, the first for males and the second for females."
